import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:hive_flutter/adapters.dart';
import 'package:provider/provider.dart';
import 'package:silent_talk/routes.dart';
import 'package:silent_talk/service/ai/ai_api.dart';
import 'package:silent_talk/service/notification/notification_shower.dart';
import 'package:silent_talk/utils/biometric/auth_provider.dart';
import 'package:silent_talk/utils/image_picker/image_picker.dart';
import 'package:silent_talk/utils/last_seen/last_seen_provider.dart';
import 'package:silent_talk/utils/localization/local_provider.dart';
import 'package:silent_talk/utils/themes/theme_data.dart';
import 'package:silent_talk/utils/themes/theme_provider.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'l10n/app_localizations.dart';

void main() async {

  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  await Hive.openBox('themes');
  await Hive.openBox('auth');
  await Hive.openBox('localBox');
  await Hive.openBox('lastSeen');
  await Hive.openBox('device_id');
  await Hive.openBox('lg');
  await Firebase.initializeApp(
    options: const FirebaseOptions(
      apiKey: "AIzaSyAwMCb9JOyl-8RCA6iPxnGlVw89AajFilc",
      appId: "1:156704193316:ios:8f808066187c855d3211b1",
      //1:156704193316:ios:8f808066187c855d3211b1  //1:156704193316:android:12088ea8a9934d143211b1
      messagingSenderId: "156704193316",
      projectId: "silenttalk-53850",
    ),
  );
  NotificationHandler.initialize();
  await Supabase.initialize(
    url: 'https://qvcdgtjxkmmtmklgffyk.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2Y2RndGp4a21tdG1rbGdmZnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMTA4ODcsImV4cCI6MjA3NTc4Njg4N30.5AyA6GGTPWCmvFtVsdvdnVXy_4m_xfxq6F8Sdz9uAtI',
  );
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => Picker()),
        ChangeNotifierProvider(create: (_) => LocaleProvider()),
        ChangeNotifierProvider(create: (_) => AuthenticateProvider()),
        ChangeNotifierProvider(create: (_) => LastSeenProvider()),
        ChangeNotifierProvider(create: (_) => AIbotApiService()),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);
    final localeProvider = Provider.of<LocaleProvider>(context);

    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      title: 'Silent Talk',

      // ✅ Localization
      locale: localeProvider.locale,
      localizationsDelegates: const [
        AppLocalizations.delegate, // generated by Flutter
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
        Locale('tr'),
        Locale('ar'),
        Locale('hy'),
      ],

      // ✅ Routing
      routerConfig: router,

      // ✅ Theme
      themeMode: themeProvider.themeMode,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
    );
  }
}

// Widget build(BuildContext context) {
//   return MaterialApp(
//     debugShowCheckedModeBanner: false,
//     title: 'Silent Talk',
//     theme: AppThemeData.lightTheme,
//     home: MainScreen(),
//   );
// }